<a href="https://colab.research.google.com/github/GuilhermeBuenoMartins/sistemas-de-inferencia-fuzzy/blob/develop/Atividade_5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [149]:
import numpy as np

def straight_equation(point_0 , point_1):
  theta_1 = (point_1[1] - point_0[1]) / (point_1[0] - point_0[0])
  theta_0 = point_1[1] - theta_1 * point_1[0]
  return (theta_0, theta_1)

def first_degree(coef, x):
  theta_0, theta_1 = coef
  y = theta_0 + theta_1 * x
  return y

def get_x(coef_, y):
  '''
  Return x value for first degree equation.

  Parameters
  ----------
  coef_ : tuple
    Tuple containing a linear and angular coefficients respectively.
    
  y: float
    Result value of sum between the linear coefficient and the product of x value and angular coefficient.

  Returns
  -------
  x
    Division result of subtraction of y and linear coefficient by angular coefficient.
  '''

  theta_0 = coef_[0]
  theta_1 = coef_[1]
  return (y - theta_0) / theta_1

def gauss_equation(x , y):
  sigma = abs(x[1] - x[0])
  mean = x[y.index(1)]
  return (mean, sigma)

def compare(point0, point1):
  return point0[0] == point1[0] and point0[1] == point1[1]

def fuzzify(vertices_, coefs_, x):
  '''
    Return a vector with degree of membership for each linguistic term.

    Parameters
    ----------
    vertex_ : list
      Matrix of points of linguist term vertices.

    coef_ : list
      Matrix of tuple of linear and angular coefficients respectively.

    x : float
      Value of x.

    Returns
    -------
    mu_ : numpy.ndarry
      Vector of degree of membership for each linguistic term.
  '''

  n = len(vertices_)
  mu_ = np.zeros((n,))
  for i in range(n):
    vertex_ = vertices_[i]
    m = len(vertex_)
    if (x <= vertex_[0][0]):
      mu_[i] = vertex_[0][1]
    elif (x > vertex_[-1][0]):
      mu_[i] = vertex_[-1][1]
    for j in range(1, m):
      if (x <= vertex_[j][0] and x > vertex_[j-1][0]):
        mu_[i] = first_degree(coef_[i][j-1], x)
  return mu_

def aggregation(mu_,term_, rule_):
  '''
    Return a dictionary with the relation between linguistic term and maximum value

  Parameters
  ----------
  mu_ : numpy.ndarray
    Degree of membership for each rule.
  
  term: list
    List of linguistic terms in order they are in the universe of discourse.

  rule_ : numpy.ndarray
    Output rule of linguistic term.

  Returns
  -------
  agg : dict
    Dictionary of maximum values for each linguistic term.
  '''

  agg = {}
  for term in term_:
    agg[term] = 0
  for term in np.unique(rule_):
    agg.update({term: np.max(mu_[rule_ == term])})
  return agg

def get_mins(var_0, var_1):
  min_ = np.array([])
  for i in var_0:
    for j in var_1:
      x = min(i, j)
      min_ = np.append(min_, x)
  return min_

 
def infer(vars_):
  n = len(vars_)
  if (n == 2):
    return get_mins(vars_[0], vars_[1])
  else:
    var0 = vars_[0]
    var1 = infer(vars_[1:n])
    return get_mins(var0, var1)


def f_o_m(universe, vertices_, coefs_, agg):
  '''
  Return a dicitonary with relation linguistic term and First of Maximums (F-o-M).

  Parameters
  ----------
  vertex_ : list
    Matrix of points of linguist term vertices.

  coef_ : list
    Matrix of tuple of linear and angular coefficients respectively.

  agg : dict
    Dictionary of degree of membership.

  Returns
  -------
  agg : dict
    Values of First of Maximums.
  '''

  n = len(vertices_)
  term_ = list(agg.keys())
  for i in range(n):
    if (agg[term_[i]] > 0):
      if (len(vertices_[i]) == 2 and coefs_[i][0][1] < 0):
        agg[term_[i]] = universe[0]
      else:
        agg.update({term_[i]: get_x(coefs_[i][0], agg[term_[i]])})
  return agg


def l_o_m(universe, vertices_, coefs_, agg):
  '''
  Return a dicitonary with relation linguistic term and Last of Maximums (L-o-M).

  Parameters
  ----------
  vertex_ : list
    Matrix of points of linguist term vertices.

  coef_ : list
    Matrix of tuple of linear and angular coefficients respectively.

  agg : dict
    Dictionary of degree of membership.

  Returns
  -------
  agg : dict
    Values of Last of Maximums.
  '''

  n = len(vertices_)
  term_ = list(agg.keys())
  for i in range(n):
    if (agg[term_[i]] > 0):
      if (len(vertices_[i]) == 2 and coefs_[i][0][1] > 0):
        agg.update({term_[i]: universe[1]})
      else:
        agg.update({term_[i]: get_x(coefs_[i][-1], agg[term_[i]])})
  return agg  


def defuzzify(rule_, agg, mu_):
  values = np.array([])
  for i in range(len(rule_)):
    values = np.append(values, agg[rule_[i]])
  sum = round(np.sum(mu_), 8)
  crisp = np.matmul(np.transpose(values), mu_) / sum
  return crisp

In [ ]:
straight_equation((0, 2), (2,-2))

(2.0, -2.0)

In [ ]:
n, m = np.shape([[2, 3, 4], [5, 6, 7], [8, 9, np.nan]])
print('n = ', n)
print('m = ', m)
arr = np.array([[2, 3, 4], [5, 6, 7], [8, 9, np.nan]])
2 <= arr[2,2]

n =  3
m =  3


False

In [ ]:
# funcs = np.array([2, 3, 3])
vertex_ = [[(0, 1), (10, 0)],
           [(0, 0), (10, 1), (20, 0)],
           [(10, 0), (20, 1), (30,0)],
           [(20, 0), (30, 1), (40,0)]]
coef_ = [[(10/10, -1/10)],
         [(0/10, 1/10), (20/10, -1/10)],
         [(-10/10, 1/10), (30/10, -1/10)],
         [(-20/10, 1/10), (40/10, -1/10)]]
x = 21
fuzzify(vertex_, coef_, x)

array([0. , 0. , 0.9, 0.1])

In [ ]:
values = (3, 5)
value_0, value_1 = values
print('Kind of values', type(values))
print('value_0', value_0)
print('value_1', value_1)

Kind of values <class 'tuple'>
value_0 3
value_1 5


In [ ]:
l = [[1, 2, 3], [3, 4, 5], [3, 5, 6]]
l.index([3, 5, 6])

2

In [ ]:
help(get_x)

Help on function get_x in module __main__:

get_x(coef_, y)
    Return x value for first degree equation.
    
    Parameters
    ----------
    coef_ : tuple
      Tuple containing a linear and angular coefficients respectively.
      
    y: float
      Result value of sum between the linear coefficient and the product of x value and angular coefficient.
    
    Returns
    -------
    x
      Division result of subtraction of y and linear coefficient by angular coefficient.



In [ ]:
get_x((2, 0.5), 3)

2.0

In [ ]:
arr = np.array([1, 2, 3, 2, 3, 5, 1, 2, 2])
np.where(arr == 2)


(array([1, 3, 7, 8]),)

In [2]:
agg = {'Vmb': 0.2, 'Vb': 3, 'Vm': 5, 'Va': 7, 'Vma': 10}
agg.items()



dict_items([('Vmb', 0.2), ('Vb', 3), ('Vm', 5), ('Va', 7), ('Vma', 10)])

In [ ]:
np.zeros((3,4)).dtype

dtype('float64')

In [ ]:
type({1: 'Vma', 2: 'Va', 3: 'Vm'})

dict

In [ ]:
help(aggregation)

Help on function aggregation in module __main__:

aggregation(mu_, rule_)
      Return a dictionary with the relation between linguistic term and maximum value
    
    Parameters
    ----------
    mu_ : numpy.ndarray
      Degree of membership for each rule
    
    rule_ : numpy.ndarray
      Output rule of linguistic term
    
    Returns
    -------
    agg : dict
      Dictionary of maximum values for each linguistic term



In [ ]:
arr = np.array([1, 2, 3, 4, 2, 3, 4, 1, 2, 4, 3])

In [ ]:
)

TypeError: ignored

In [ ]:
agg.update({'a': 3})
agg.update({'a': 1})
agg

{'a': 1}

In [ ]:
var0 = np.array([0, 1])
var1 = np.array([0.5, 0.0, 0.0, 0.0])
var2 = np.array([0.25, 0.25, 0.0, 0.0])
infer([var0, var1, var2])

array([0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  ,
       0.  , 0.  , 0.  , 0.  , 0.  , 0.25, 0.25, 0.  , 0.  , 0.  , 0.  ,
       0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  ])

In [142]:
rule_ = np.array(['Vma', 'Vma', 'Vma', 'Vma', 'Va', '-', '-','Vma','Vma',  'Vma', 'Va', 'Va', '-', '-', 'Vma','Vma', 'Vma', 'Va', 'Vm','-', '-',
 'Vma', 'Vma', 'Va', 'Va', 'Vm', '-', '-', 'Vma', 'Vma', 'Va', 'Vm', 'Vb', '-', '-', 'Vma', 'Vma', 'Va', 'Vm', '-', '-', '-',
 'Vma', 'Vma', 'Va', 'Vm', '-', '-', '-', 'Vma', 'Va', 'Vm', 'Vb', '-', '-', '-', 'Va', 'Vm', 'Vm', 'Vb', '-', '-', '-', 
'Va','Vm', 'Vb', 'Vmb', '-', '-', '-'])

mu_ = np.array([0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 
                0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.25, 0.1, 0.0, 0.0, 0.0, 0.0, 0.0, 0.75, 0.1, 0.0, 0.0, 
                0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0])

aggregation(mu_, rule_)



TypeError: ignored

In [ ]:
np.array([[[0, 1], [10, 11]], [[20, 21], [30, 31]]])

array([[[ 0,  1],
        [10, 11]],

       [[20, 21],
        [30, 31]]])

In [ ]:
rule_ = np.array(['Muito pouco', 'Pouco', 'Moderado', 'Moderado', 'Pouco', 'Pouco', 'Moderado', 'Exagerado', 'Moderado', 
                  'Moderado', 'Exagerado', 'Exagerado', 'Moderado', 'Exagerado', 'Máximo', 'Máximo', 'Muito pouco', 
                  'Pouco', 'Moderado', 'Moderado', 'Pouco', 'Pouco', 'Moderado', 'Exagerado', 'Moderado', 
                  'Moderado', 'Exagerado', 'Exagerado', 'Moderado', 'Exagerado', 'Máximo', 'Máximo'])

mu_ = np.array([0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  ,
                0.  , 0.  , 0.  , 0.  , 0.  , 0.25, 0.25, 0.  , 0.  , 0.  , 0.  ,
                0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.])

agg = aggregation(mu_, rule_)

In [ ]:
agg['Muito pouco'] = 10
agg['Pouco'] = 30
values = np.array([])
for i in range(len(rule_)):
  values = np.append(values, agg[rule_[i]])
values

array([10., 30.,  0.,  0., 30., 30.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0., 10., 30.,  0.,  0., 30., 30.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.])

In [ ]:
np.average(values, weights=mu_)

20.0

In [ ]:
sugeno = np.array([010.0, 030.0, 060.0, 060.0,
                   030.0, 030.0, 060.0, 080.0,
                   060.0, 060.0, 080.0, 080.0,
                   060.0, 080.0, 100.0, 100.0,
                   010.0, 030.0, 060.0, 060.0,
                   030.0, 030.0, 060.0, 080.0,
                   060.0, 060.0, 080.0, 080.0,
                   060.0, 080.0, 100.0, 100.0])
np.average(sugeno, weights=mu_)

20.0

In [ ]:
var0_ = np.array([[0], [1], [3], [4], [5]])
var1_ = np.array([[0], [1], [3], [4]])
var2_ = np.array([[0], [1], [2]])

test(var0_, var1_, var2_)


(array([[0],
        [1],
        [3],
        [4],
        [5]]), array([[0],
        [1],
        [3],
        [4]]))

In [ ]:
arr = []
arr.append(0)

In [ ]:
arr

[0]

In [ ]:
np.shape(rule_)[0]

32

In [40]:
def f_o_m(universe, vertices_, coefs_, agg):
  '''
  Return a dicitonary with relation linguistic term and First of Maximums (F-o-M).

  Parameters
  ----------
  vertex_ : list
    Matrix of points of linguist term vertices.

  coef_ : list
    Matrix of tuple of linear and angular coefficients respectively.

  agg : dict
    Dictionary of degree of membership.

  Returns
  -------
  agg : dict
    Values of First of Maximums.
  '''

  n = len(vertices_)
  term_ = list(agg.keys())
  for i in range(n):
    if (agg[term_[i]] > 0):
      if (len(vertices_[i]) == 2 and coefs_[i][0][1] < 0):
        agg[term_[i]] = universe[0]
      else:
        agg.update({term_[i]: get_x(coefs_[i][0], agg[term_[i]])})
  return agg

def l_o_m(universe, vertices_, coefs_, agg):
  '''
  Return a dicitonary with relation linguistic term and Last of Maximums (L-o-M).

  Parameters
  ----------
  vertex_ : list
    Matrix of points of linguist term vertices.

  coef_ : list
    Matrix of tuple of linear and angular coefficients respectively.

  agg : dict
    Dictionary of degree of membership.

  Returns
  -------
  agg : dict
    Values of Last of Maximums.
  '''

  n = len(vertices_)
  term_ = list(agg.keys())
  for i in range(n):
    if (agg[term_[i]] > 0):
      if (len(vertices_[i]) == 2 and coefs_[i][0][1] > 0):
        agg.update({term_[i]: universe[1]})
      else:
        agg.update({term_[i]: get_x(coefs_[i][-1], agg[term_[i]])})
  return agg  

In [ ]:
agg = {'Vma': 0, 'Vm': 0, 'Va': 1, 'Vb': 0, 'Vmb': 0}
agg.items()

dict_items([('Vma', 0), ('Vm', 0), ('Va', 1), ('Vb', 0), ('Vmb', 0)])

In [ ]:
agg['Va'] = 0.25
agg['Vb'] = 0.75
for i in agg.keys():
  print(i)

Vma
Vm
Va
Vb
Vmb


In [153]:
agg = {'Vmb': 0.5, 'Vb': 0.75, 'Vm': 0.25,'Va': 0, 'Vma': 0.5, '-': 0}
vertices_ = [[(1,1), (3,0)],
             [(1,0), (3,1), (5,0)],
             [(3,0), (5,1), (7,0)],
             [(5,0), (7,1), (9,0)],
             [(7,0), (9,1)]]
coefs_ = [[(3/2,-1/2)],
          [(-1/2,1/2), (5/2,-1/2)],
          [(-3/2,1/2), (7/2,-1/2)],
          [(-5/2,1/2), (9/2,-1/2)],
          [(-7/2,1/2)]]
universe = (0, 10)
agg = f_o_m(universe, vertices_, coefs_, agg)


In [154]:
agg

{'-': 0, 'Va': 0, 'Vb': 2.5, 'Vm': 3.5, 'Vma': 8.0, 'Vmb': 0}

In [146]:
agg = {'Vmb': 0.2, 'Vb': 3, 'Vm': 5, 'Va': 7, 'Vma': 10, '-': 0}
rule_ = ['Vma', 	'Vma', 	'Vma', 	'Vma', 	'Va', 	'-', 	'-', 
         'Vma', 	'Vma', 	'Vma', 	'Va', 	'Va', 	'-', 	'-', 
         'Vma', 	'Vma', 	'Vma', 	'Va', 	'Vm', 	'-', 	'-', 
         'Vma', 	'Vma', 	'Va', 	'Va', 	'Vm', 	'-', 	'-', 
         'Vma', 	'Vma', 	'Va', 	'Vm', 	'Vb', 	'-', 	'-',
         'Vma', 	'Vma', 	'Va', 	'Vm', 	'-', 	'-', 	'-', 
         'Vma', 	'Vma', 	'Va', 	'Vb', 	'-', 	'-', 	'-', 
         'Vma', 	'Va', 	'Vm', 	'Vb', 	'-', 	'-', 	'-', 
         'Va', 	'Vm', 	'Vm', 	'Vb', 	'-', 	'-', 	'-',
         'Va', 	'Vm', 	'Vb', 	'Vmb', 	'-', 	'-', 	'-']
mu_ = np.array([0, 0, 0, 0, 0, 0 , 0,
       0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0,
       0, 0, 0.25, 0.1, 0, 0, 0,
       0, 0, 0.75, 0.1, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0], )


In [150]:
defuzzify(rule_, agg, mu_)

6.5

In [148]:
sum(mu_)

1.2000000000000002

In [174]:
def get_coefs_(vertices_):
  coefs_ = []
  for vertex_ in vertices_:
    i = vertices_.index(vertex_)
    m = len(vertex_)
    coef_ = []
    for j in range(m-1):
      coef_.append(straight_equation(vertex_[j], vertex_[j+1]))
    coefs_.append(coef_)
  return coefs_

In [175]:
coefs_

[[(1.5, -0.5)],
 [(-0.5, 0.5), (2.5, -0.5)],
 [(-1.5, 0.5), (3.5, -0.5)],
 [(-2.5, 0.5), (4.5, -0.5)],
 [(-3.5, 0.5)]]

In [176]:
get_coefs_(vertices_)

[[(1.5, -0.5)],
 [(-0.5, 0.5), (2.5, -0.5)],
 [(-1.5, 0.5), (3.5, -0.5)],
 [(-2.5, 0.5), (4.5, -0.5)],
 [(-3.5, 0.5)]]

# Implmentação do código

In [ ]:
class Fuzzy():


  def fuzzify(vertices_, coefs_, x):
  '''
    Return a vector with degree of membership for each linguistic term.

    Parameters
    ----------
    vertex_ : list
      Matrix of points of linguist term vertices.

    coef_ : list
      Matrix of tuple of linear and angular coefficients respectively.

    x : float
      Value of x.

    Returns
    -------
    mu_ : numpy.ndarry
      Vector of degree of membership for each linguistic term.
  '''

  n = len(vertices_)
  mu_ = np.zeros((n,))
  for i in range(n):
    vertex_ = vertices_[i]
    m = len(vertex_)
    if (x <= vertex_[0][0]):
      mu_[i] = vertex_[0][1]
    elif (x > vertex_[-1][0]):
      mu_[i] = vertex_[-1][1]
    for j in range(1, m):
      if (x <= vertex_[j][0] and x > vertex_[j-1][0]):
        mu_[i] = CalcsAndOps().first_degree(coef_[i][j-1], x)
  return mu_


  def infer(vars_):
    '''
    Return the list resultant of the calculus of consequent.

    Parameters
    ----------
    vars_ : list
      List that contend the variables with its degrees of membership

    Returns
    -------
    gets_mins
      A list of minimization of variables.
    '''

    n = len(vars_)
    if (n == 2):
      return get_mins(vars_[0], vars_[1])
    else:
      var0 = vars_[0]
      var1 = infer(vars_[1:n])
      return get_mins(var0, var1)


  def aggregation(mu_,term_, rule_):
  '''
    Return a dictionary with the relation between linguistic term and maximum value

  Parameters
  ----------
  mu_ : numpy.ndarray
    Degree of membership for each rule.
  
  term: list
    List of linguistic terms in order they are in the universe of discourse.

  rule_ : numpy.ndarray
    Output rule of linguistic term.

  Returns
  -------
  agg : dict
    Dictionary of maximum values for each linguistic term.
  '''

  agg = {}
  for term in term_:
    agg[term] = 0
  for term in np.unique(rule_):
    agg.update({term: np.max(mu_[rule_ == term])})
  return agg


  def f_o_m(universe, vertices_, coefs_, agg):
    '''
    Return a dicitonary with relation linguistic term and First of Maximums (F-o-M).

    Parameters
    ----------
    universe: tuple
      Definition of universe of discourse in a ordered pair with minimum and maximum 
      values respectively.

    vertex_ : list
      Matrix of points of linguist term vertices.

    coef_ : list
      Matrix of tuple of linear and angular coefficients respectively.

    agg : dict
      Dictionary of degree of membership.

    Returns
    -------
    agg : dict
        A dictionary contends the relation of terms linguistics and of Last of 
        Maximums.
    '''

    n = len(vertices_)
    term_ = list(agg.keys())
    for i in range(n):
      if (agg[term_[i]] > 0):
        if (len(vertices_[i]) == 2 and coefs_[i][0][1] < 0):
          agg[term_[i]] = universe[0]
        else:
          agg.update({term_[i]: get_x(coefs_[i][0], agg[term_[i]])})
    return agg


  def l_o_m(universe, vertices_, coefs_, agg):
    '''
    Return a dicitonary with relation linguistic term and Last of Maximums (L-o-M).

    Parameters
    ----------
    universe: tuple
      Definition of universe of discourse in a ordered pair with minimum and maximum 
      values respectively.

    vertex_ : list
      Matrix of points of linguist term vertices.

    coef_ : list
      Matrix of tuple of linear and angular coefficients respectively.

    agg : dict
      Dictionary of degree of membership.

    Returns
    -------
    agg : dict
        A dictionary contends the relation of terms linguistics and of Last of 
        Maximums.
    '''

    n = len(vertices_)
    term_ = list(agg.keys())
    for i in range(n):
      if (agg[term_[i]] > 0):
        if (len(vertices_[i]) == 2 and coefs_[i][0][1] > 0):
          agg.update({term_[i]: universe[1]})
        else:
          agg.update({term_[i]: get_x(coefs_[i][-1], agg[term_[i]])})
    return agg  


    def mamdani_defuz(rule_, agg, mu_):
      '''
      Return result of Crisp variable from average calc for Mamdani's 
      deffuzification.

      Parameters
      ----------
      rule_ : list
        A list of rules with linguistic terms for each degree of membership output.

      agg: dict
        A dictionary contends the relation of terms linguistics and found values of
        x from degree of membership

      mu_ : list
        List of degrees of membership after calculus of minimization of rules.

      Returns
      -------
      crisp: float
        Value of variable Crisp.
      '''

    values = np.array([])
    for i in range(len(rule_)):
      values = np.append(values, agg[rule_[i]])
    sum = round(np.sum(mu_), 8)
    crisp = np.matmul(np.transpose(values), mu_) / sum
    return crisp


    def sugeno_defuz(values, mu_):
          '''
      Return result of Crisp variable from average calc for Takagi-Sugeno's
      approach

      Parameters
      ----------
      rule_ : list
        A list of rules with linguistic terms for each degree of membership output.

      agg: dict
        A dictionary contends the relation of terms linguistics and found values of
        x from degree of membership

      mu_ : list
        List of degrees of membership after calculus of minimization of rules.

      Returns
      -------
      crisp: float
        Value of variable Crisp.
      '''

      sum = round(np.sum(mu_), 8)
      crisp = np.matmul(np.transpose(values), mu_) / sum
      return crisp


In [ ]:
class CalcsAndOps():

  def straight_equation(point_0 , point_1):
    '''
    Return linear and angular coefficients in an tuple.

    Parameters
    ----------
    point_0 : tuple
      A tuple correspondent to first point (x, y).

    point_1 : tuple
      A tuple correspondent to second point (x, y).

    Returns
    -------
    coef_ : tuple
      A tuple correspondent to the linear and angular coefficients. 
    '''
    theta_1 = (point_1[1] - point_0[1]) / (point_1[0] - point_0[0])
    theta_0 = point_1[1] - theta_1 * point_1[0]
    return (theta_0, theta_1)

def first_degree(coef, x):
  '''
  Return value of y for a first degree equation using linear and angular
  coefficients and, x.

  Parameters
  ----------
  coef : tuple
    Tuple containing a linear and angular coefficients respectively.

  x : float
    Value of input x.
  Returns
  -------
  y : float
    Value of y for a first degree equation.
  '''

  theta_0, theta_1 = coef
  y = theta_0 + theta_1 * x
  return y
  

def get_x(coef_, y):
  '''
  Return x value for first degree equation.

  Parameters
  ----------
  coef_ : tuple
    Tuple containing a linear and angular coefficients respectively.
    
  y: float
    Result value of sum between the linear coefficient and the product of x value and angular coefficient.

  Returns
  -------
  x
    Division result of subtraction of y and linear coefficient by angular coefficient.
  '''

  theta_0 = coef_[0]
  theta_1 = coef_[1]
  return (y - theta_0) / theta_1

def get_mins(var_0, var_1):
  '''
  Return a list of minors values. since of two list of values.
  
  Parameters
  ----------
  var_0 : list
    List of values owners the first variable

  var_1: list
    List of values owners the first variable

  Returns
  -------
  min_
    List of minors values.
  '''
  min_ = np.array([])
  for i in var_0:
    for j in var_1:
      x = min(i, j)
      min_ = np.append(min_, x)
  return min_